version: "3.8"
services:
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd123!!!"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
